import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/elements/navbar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { sfPro } from "./fonts";
import DndProviderWrapper from "@/components/providers/dndProvider";
import { FormProvider } from "@/context/form-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* React Scan for development */}
      {process.env.NODE_ENV === "development" &&
        <head>
          <script src="https://unpkg.com/react-scan/dist/auto.global.js" />
        </head>
      }
      <body
        className={`${sfPro.className} antialiased`}
      >
        <Navbar />
        <SessionProvider>
          <DndProviderWrapper>
            <FormProvider initialData={{
              title: "",
              description: "",
              sections: []
            }}>
              {children}
            </FormProvider>
          </DndProviderWrapper>
        </SessionProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
